# Generated by Django 4.0.2 on 2022-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, to='website.Dish'),
        ),
    ]
